export interface TarotCard {
  id: number
  name: string
  arcana: 'Major' | 'Minor'
  suit: 'major' | 'wands' | 'cups' | 'swords' | 'pentacles'
  number?: number
  keywords: string[]
  upright_meaning: string
  reversed_meaning: string
  description: string
  love: string
  career: string
  advice: string
  emotional_message: string
  image: string
}

export const tarotCards: TarotCard[] = [
  // Major Arcana
  {
    id: 0,
    name: 'The Fool',
    arcana: 'Major',
    suit: 'major',
    number: 0,
    keywords: ['new beginnings', 'innocence', 'risk', 'adventure'],
    upright_meaning: 'New beginnings, innocence, spontaneity, free spirit',
    reversed_meaning: 'Recklessness, risk-taking, naivety, poor decisions',
    description: 'The Fool represents new beginnings and having faith in the future. He is stepping forward into the unknown, trusting that the universe will guide him.',
    love: "Naya pyaar ka intertain hai yaar! Agar koi naya person mila hai toh daraao mat - be confident and see where it goes. Dekho, har rishta shuru mein darrlagta hai, par yeh faayda hai ki tum free feel kar rahe ho.",
    career: "Career ke liye yeh card bohot positive hai! Naya opportunity ya project mil sakta hai. Agar resume bhejna hai ya interview ke liye jaana hai toh perfect timing hai. Tum abhi jo bhi kar rahe ho, apne aap par trust rakhna hai.",
    advice: "Jao aur try karo! Dekho, tension lene ki koi baat nahi - bas thoda careful raho. Naye logon se milna, naye experiences try karna is the way forward. Tum ready ho for this new adventure.",
    emotional_message: "Dekho yaar, thoda darr naturally hai jab koi naya shuru hota hai. But tum strong ho - I know it! Bas apne dil ki suno aur jo feeling sach mein sahi lage, wahi karo. Tum handle kar loge 💜",
    image: '🃏',
  },
  {
    id: 1,
    name: 'The Magician',
    arcana: 'Major',
    suit: 'major',
    number: 1,
    keywords: ['manifestation', 'power', 'skill', 'concentration'],
    upright_meaning: 'Manifestation, resourcefulness, power, inspired action',
    reversed_meaning: 'Manipulation, poor planning, untapped talents, deception',
    description: 'The Magician represents the ability to manifest your desires through willpower and skill. He has all the tools he needs to succeed.',
    love: "Tum abhi apni full potential ke saath love mein engaged ho! Agar koi attraction hai toh express karo - timing perfect hai. Tumhe jo chahiye woh manifest kar sakte ho. Confidence se ao, sab set hai!",
    career: "Work mein abhi tumhe resources milenge jo tumhe chahiye. Agar koi project ke liye opportunities chahte ho toh ab perfect time hai. Tumari skills ka poora faayda uthao - tumhe jitna mileage chahiye utna milega. Go for it!",
    advice: "Ab apni power realize karo! Tumhe jitne tools chahiye woh sab tumhare paas already hai. Jo bhi tumhe chahiye, use create karo. Don't wait - directly make it happen. Action lena abhi, bas yahi perfect time hai.",
    emotional_message: "Tum actually bohot powerful ho! Aur yeh realize karna sabse important hai. Tum jo bhi chahte ho, woh paane ki capacity tumhari andar hai. Bas thoda faith in yourself rakhna hai. You've got this! 💜",
    image: '🎭',
  },
  {
    id: 2,
    name: 'The High Priestess',
    arcana: 'Major',
    suit: 'major',
    number: 2,
    keywords: ['intuition', 'mystery', 'subconscious', 'inner knowledge'],
    upright_meaning: 'Intuition, sacred knowledge, divine feminine, subconscious',
    reversed_meaning: 'Secrets, disconnected from intuition, withdrawal, surface-level',
    description: 'The High Priestess represents intuition, mystery, and inner knowledge. She sits between the conscious and subconscious worlds.',
    love: "Agar koi relationship mein confusion hai toh apni intuition par trust karo. Tumhe jo feeling aa rahi hai woh sahi hai - darr lagta hai par koi inner knowing hai. Koi baat jo tumhe lag rahi hai woh feel karo!",
    career: "Professional decisions mein apni inner voice suno. Koi deal ya opportunity ke baare mein agar tumhe kuch feel ho raha hai, woh important hai. Thoda research karo but ultimately tumhara gut feel sach hai.",
    advice: "Apni intuition par trust karo - jo baat dil mein bol rahi hai woh sahi hai. Aur thoda meditation ya reflection karo, kyunki answers bahar nahi inner hai. Quiet time lo aur socho ki真正 kya chahiye.",
    emotional_message: "Tumara heart jo bol raha hai woh sach hai. Agar koi situation confuse lag rahi hai toh thoda pause karo aur inner self se baat karo. Tumhe sab answers already paas hai, bas thoda sunnyane ki zaroorat hai. Tumhara intuition strong hai! 💜",
    image: '🌙',
  },
  {
    id: 3,
    name: 'The Empress',
    arcana: 'Major',
    suit: 'major',
    number: 3,
    keywords: ['abundance', 'nurturing', 'fertility', 'beauty'],
    upright_meaning: 'Femininity, beauty, nature, nurturing, abundance',
    reversed_meaning: 'Creative block, dependence on others, emptiness, neglect',
    description: 'The Empress represents abundance, nurturing, and the beauty of nature. She is the mother figure of the tarot.',
    love: "Love mein abundance aane wali hai! Relationship mein thoda softness aur nurturing ki zaroorat hai. Apne partner ko aur apne aap ko care karo. Fertility aur family planning ke liye bhi yeh card positive hai.",
    career: "Creative fields mein bohot faayda hai! Design, art, food, hospitality - koi bhi creative field ho, opportunities atke hain. Work environment ko thoda comfortable aur welcoming banana helps. Abundance align ho raha hai tumahara career.",
    advice: "Soften up a bit - harshness ki jagah love se kaam lo. Jab logon se baat karo thoda warmth ke saath karo. Creative side ko express karne ka time aagaya hai. Abundance accept karo aur appreciate karo jo tumhare paas hai.",
    emotional_message: "Tum deserve karo ki pyaar kiya jao aur appreciate kiya jao. Thoda apne aap ko extra love dena - jo tum doongi woh wapas bhi milegi. Relationships mein warmth aur care ka feel rakho. You've got so much love to give! 💜",
    image: '👑',
  },
  {
    id: 4,
    name: 'The Emperor',
    arcana: 'Major',
    suit: 'major',
    number: 4,
    keywords: ['authority', 'structure', 'control', 'leadership'],
    upright_meaning: 'Authority, structure, control, fatherhood, leadership',
    reversed_meaning: 'Domination, excessive control, lack of discipline, rigidity',
    description: 'The Emperor represents authority, structure, and control. He is the father figure of the tarot.',
    love: "Relationship mein thoda boundaries aur structure chahiye. Koi baat define karo - kya tum dono chahte ho, clarity rakhna hai. Leadership lene ki zaroorat hai. Control haathaanaana.",
    career: "Leadership role ki tayyari ho rahi hai! Promotion ya managerial position mil sakta hai. Professional structure aur discipline se kaam paiseenge. Tum strongest version ho - apne authority use karo.",
    advice: "Structure create karo apni life mein. Goals set karo aur unpe kaam karo. Discipline rakhna hai aur consistency rakhna hai. Leadership lene ke liye ready raho - abhi perfect time hai lead karne ka.",
    emotional_message: "Tum strong ho aur strong leader ho. Darr mat lo apni responsibilities se - tum handle kar sakte ho. Thoda control rakho, par rigid mat bano. Balance rakhna hai authority aur warmth ke beech. You've got the power in you! 💜",
    image: '🏛️',
  },
  {
    id: 5,
    name: 'The Hierophant',
    arcana: 'Major',
    suit: 'major',
    number: 5,
    keywords: ['tradition', 'spirituality', 'conformity', 'beliefs'],
    upright_meaning: 'Spiritual wisdom, religious beliefs, conformity, tradition',
    reversed_meaning: 'Personal beliefs, freedom, challenging the status quo',
    description: 'The Hierophant represents spiritual wisdom and religious beliefs. He is the bridge between heaven and earth.',
    love: "Traditional values aur long-term commitment is time important hai. Marriage ya engagement ki baat ho sakti hai. Religion ya spirituality ki basis par relationship strong hogi. Conformity se fayda hai.",
    career: "Traditional industries ya established companies faayda mand honge. Education, law, religious organizations - yeh fields strong hain. Training ya mentorship mil sakta hai. Formal approach best hai.",
    advice: "Traditional values se advice lo. Gurus ya mentors se seekho. Established systems follow karo. Koi bhi field ho, traditional knowledge seekhna faayda mand hai. Structured learning ka time hai.",
    emotional_message: "Tumhare paas strong beliefs hain aur woh valuable hain. Apne values par stand rakhna hai - yeh tumhe strong banata hai. Par thoda flexibility bhi rakhna hai. Traditional wisdom powerful hai! 💜",
    image: '📿',
  },
  {
    id: 6,
    name: 'The Lovers',
    arcana: 'Major',
    suit: 'major',
    number: 6,
    keywords: ['love', 'harmony', 'relationships', 'choices'],
    upright_meaning: 'Love, harmony, relationships, choices, alignment',
    reversed_meaning: 'Self-love, disharmony, imbalance, misalignment, conflict',
    description: 'The Lovers represent love, harmony, and relationships. They also represent choices and alignment of values.',
    love: "Perfect love card! Harmony aur deep connection aane wala hai. Values align hain - agar relationship mein doubts the, toh yeh clear ho jayenge. Deep emotional bond ban sakta hai. Choose wisely.",
    career: "Partnership ya collaboration ke liye excellent time! Joint ventures faayda mand honge. Work partner mil sakta hai ya business partnership ho sakti hai. Team harmony badh jayega.",
    advice: "Choice important hai - socho ki tum kya chahte ho. Values alignment dekho. Relationship ya partnership ki terms clear karo. Do not rush - take your time to decide what's right for you.",
    emotional_message: "True love achievable hai! Bas thoda patience rakhna hai aur apne feelings par trust rakhna hai. Jo sach mein worth hai woh milta hai. Tumahara perfect partner kahin na kahin hai 💜",
    image: '💕',
  },
  {
    id: 7,
    name: 'The Chariot',
    arcana: 'Major',
    suit: 'major',
    number: 7,
    keywords: ['control', 'willpower', 'success', 'determination'],
    upright_meaning: 'Control, willpower, success, action, determination',
    reversed_meaning: 'Self-discipline, opposition, lack of direction, aggression',
    description: 'The Chariot represents control, willpower, and success. He moves forward with determination and focus.',
    love: "Koi baat jeetna hai! Relationship mein agar competition hai toh win karne ka samay hai. Determination se apna goal achieve karo. Strong will se relationship mein aage badho.",
    career: "Career victory ke liye time hai! Promotion, deal, ya koi big achievement mil sakta hai. Focus rakho aur apna target achieve karo. Willpower se sab kar sakte ho.",
    advice: "Willpower use karo - focus rakhna hai aur apna goal achieve karna hai. Control apne hath mein rakhna hai. Derge na ho, abhi action lena hai. Success tumhare raste mein hai!",
    emotional_message: "Tum super strong ho! Jo bhi challenge hai, tum jeet sakte ho. Bas focus rakhna hai aur apni power realize karna hai. Tum can do this - I believe in you! 💜",
    image: '⚔️',
  },
  {
    id: 8,
    name: 'Strength',
    arcana: 'Major',
    suit: 'major',
    number: 8,
    keywords: ['strength', 'courage', 'patience', 'control'],
    upright_meaning: 'Strength, courage, persuasion, influence, compassion',
    reversed_meaning: 'Inner strength, self-doubt, low energy, weakness',
    description: 'Strength represents courage, compassion, and inner strength. She tames the lion with love, not force.',
    love: "Gentle power use karo! Relationship mein coerce mat karo - love se influence karo. Patience rakhna hai aur compassion se kaam lena hai. Tum jante ho ki pyaar se zyada strong kuch nahi.",
    career: "Soft skills ki power se kaam paiseenge. Persuasion, negotiation - yeh abilities useful honge. Leadership mein harshness ki jagah compassion se kaam lo. Tum naturally influential ho - use that!",
    advice: "Internal strength use karo - external force ki jagah inner power se kaam karo. Patience rakhna hai aur gentleness se apna samay lo. Pyaar aur compassion sabke se powerful hai. Tum naturally strong ho!",
    emotional_message: "Tum actually bohot strong ho - aur tumhe yeh realize nahi hota! Jo bhi situation hai, tum usse handle kar sakte ho. Gentle power se zyada kuch achieve hota hai. Trust yourself! 💜",
    image: '🦁',
  },
  {
    id: 9,
    name: 'The Hermit',
    arcana: 'Major',
    suit: 'major',
    number: 9,
    keywords: ['introspection', 'solitude', 'guidance', 'wisdom'],
    upright_meaning: 'Soul-searching, introspection, being alone, inner guidance',
    reversed_meaning: 'Isolation, loneliness, withdrawal, social isolation',
    description: 'The Hermit represents soul-searching and introspection. He seeks inner guidance and wisdom.',
    love: "Solitude time hai! Relationship ke liye ready honge tabhi aage badho jab inner self clear ho. Koi baat socho ki tum kya chahte ho. Alag time lena aur apne aap se baat karo.",
    career: "Personal growth time hai! Thoda alag time lena aur career socho. Next steps decide karo. Professional guidance ya mentorship seekhna faayda mand hai. Introspection se clarity aayegi.",
    advice: "Alag time lo - thoda solitude is important. Inner self se baat karo aur socho ki真正 kya chahiye. Meditation ya reflection karo. Guidance bahar nahi andhar hai. Answers tumhare paas hain.",
    emotional_message: "Thoda alag time lena zyada burra nahi hai. Actually important hai ki tum apne aap se connect karo. Jo answers dhundh rahe ho woh already tumhare paas hain. Solitude se clarity aayegi! 💜",
    image: '🏔️',
  },
  {
    id: 10,
    name: 'Wheel of Fortune',
    arcana: 'Major',
    suit: 'major',
    number: 10,
    keywords: ['luck', 'karma', 'cycles', 'destiny'],
    upright_meaning: 'Good luck, karma, life cycles, destiny, turning point',
    reversed_meaning: 'Bad luck, resistance to change, breaking cycles, misfortune',
    description: 'The Wheel of Fortune represents the cycles of life and destiny. What goes up must come down.',
    love: "Destiny love mein intervene kar rahi hai! Agar koi connection fated hai toh mil jayega. Life cycles change ho rahe hain - new chapter shuru ho sakti hai. Luck tumhari side hai. Koi unexpected meeting possible hai.",
    career: "Unexpected opportunity aane wali hai! Luck tumhare saath hai. New project, promotion ya unexpected break mil sakta hai. Cycle change ho raha hai - ready raho for new beginnings.",
    advice: "Cycle change ho raha hai - isse fight mat karo. Luck ab tumhare saath hai! Naye opportunities accept karo. Jo aayega woh good hai. Trust the process aur ready raho for new things.",
    emotional_message: "Change good hai! Tumahara luck ab upar ja raha hai. Jo bhi situation thi woh badalne wali hai. Naya kuch shuru hone wali hai - excited raho! Your lucky period is here! 💜",
    image: '☸️',
  },
  {
    id: 11,
    name: 'Justice',
    arcana: 'Major',
    suit: 'major',
    number: 11,
    keywords: ['justice', 'fairness', 'truth', 'law'],
    upright_meaning: 'Justice, fairness, truth, cause and effect, law',
    reversed_meaning: 'Unfairness, lack of accountability, dishonesty, evasion',
    description: 'Justice represents fairness, truth, and the law of cause and effect. Every action has a consequence.',
    love: "Fairness relationship mein important hai! What you give is what you get. Equality par focus karo. Koi imbalance hai toh address karo. Honest communication is key.",
    career: "Legal matters resolve ho sakte hain! Professional fairness important hai. What you deserve woh milega. Credit mil sakta hai. Honesty se kaam karo.",
    advice: "Fair aur honest raho. Jo tum karte ho woh wapas aayega. Balance maintain karo. Justice will be served - be patient aur fair.",
    emotional_message: "Tum deserve karte ho jo sahi hai. Fairness important hai tumhe aur tumhe woh milega bhi. Honest raho aur tumahara karma good hai. Koi injustice ab address hogi! 💜",
    image: '⚖️',
  },
  {
    id: 12,
    name: 'The Hanged Man',
    arcana: 'Major',
    suit: 'major',
    number: 12,
    keywords: ['surrender', 'perspective', 'letting go', 'sacrifice'],
    upright_meaning: 'Pause, surrender, letting go, new perspectives',
    reversed_meaning: 'Delays, resistance, stalling, indefinite pause',
    description: 'The Hanged Man represents surrender and seeing things from a new perspective. Sometimes you must let go to move forward.',
    love: "Pause karo! Relationship mein rush mat karo. Socho ki kya tumhe really chahiye. New perspective se dekho situation ko. Letting go zaroori hai to move forward.",
    career: "Delays possible hain! Thoda patience rakhna hai. Career decisions mein rush mat karo. New perspective se socho - different angle se dekho. Suspension is temporary.",
    advice: "Pause karo - abhi koi big decision mat lo. Let things settle ho jayein. Different perspective se socho. Sometimes you need to wait to move forward.",
    emotional_message: "Thoda sa pause lena zyada burra nahi hai! Actually isse clarity aayegi. Socho thoda - patience aur new perspective se. Things will make sense soon! 💜",
    image: '🙃',
  },
  {
    id: 13,
    name: 'Death',
    arcana: 'Major',
    suit: 'major',
    number: 13,
    keywords: ['transformation', 'endings', 'change', 'transition'],
    upright_meaning: 'Endings, change, transformation, rebirth, new beginnings',
    reversed_meaning: 'Resistance to change, feared endings, stagnation',
    description: 'Death represents endings and transformation. It is not physical death, but the end of a cycle.',
    love: "Transformation time hai! Old pattern end ho raha hai - yeh good hai! Relationship mein koi chapter close ho raha hai aur naya shuru hoga. Change embrace karo.",
    career: "Old career chapter end ho raha hai! New beginning ke signals hain. Job change, promotion, or major shift possible hai. Endings are just new beginnings.",
    advice: "Change embrace karo! Old end ho raha hai toh naya better aayega. Resistance mat karo - let go karo. Transformation is natural aur good!",
    emotional_message: "Endings scary lagti hain par actually yeh good hai! Jo khatam ho raha hai woh necessary hai. Naya aur better coming your way! Transformation is powerful 💜",
    image: '💀',
  },
  {
    id: 14,
    name: 'Temperance',
    arcana: 'Major',
    suit: 'major',
    number: 14,
    keywords: ['balance', 'moderation', 'patience', 'harmony'],
    upright_meaning: 'Balance, moderation, patience, purpose, harmony',
    reversed_meaning: 'Imbalance, excess, lack of patience, discord',
    description: 'Temperance represents balance, moderation, and patience. She blends opposites to create something new.',
    love: "Balance important hai! Relationship mein doono taraf se effort chahiye. Patience rakhna hai aur moderation se kaam karo. Harmony create karo. Too much ya too less - balance chahiye!",
    career: "Work-life balance important! Overworking se burra hota hai. Patience rakhna hai - success aayegi. Moderate approach se kaam karo. Balance maintain karo.",
    advice: "Balance rakhna hai! Too much anything is bad. Moderate karo, patience rakhna hai. Doono taraf se socho. Moderation is key to harmony.",
    emotional_message: "Balance is the answer! Thoda slow down karo. Patience rakhna hai aur moderate raho. Jo bhi situation hai, usme balance dhundho! 💜",
    image: '⚗️',
  },
  {
    id: 15,
    name: 'The Devil',
    arcana: 'Major',
    suit: 'major',
    number: 15,
    keywords: ['attachment', 'shadow', 'restriction', 'addiction'],
    upright_meaning: 'Shadow self, attachment, addiction, restriction, materialism',
    reversed_meaning: 'Releasing limiting beliefs, exploring dark thoughts, freedom',
    description: 'The Devil represents shadow self and attachment. He shows us what holds us back.',
    love: "Attachment ya codependency issues ho sakti hain! Check karo ki kya tum over-attached ho. Freedom important hai. Control release karo.",
    career: "Work addiction ya materialism ho sakti hai! Money ki obsession se burra hota hai. Check karo ki kya tum obsessive ho. Balance chahiye.",
    advice: "Limiting beliefs release karo! Kya cheezein tumhe restrict kar rahi hain unhe identify karo. Freedom select karo. Limiting beliefs se free hona important hai.",
    emotional_message: "Tum free ho! Jo shackles lag rahe hain unhe hatao. Tum strong ho aur free ho. Limiting beliefs se free hona zaroori hai! 💜",
    image: '😈',
  },
  {
    id: 16,
    name: 'The Tower',
    arcana: 'Major',
    suit: 'major',
    number: 16,
    keywords: ['upheaval', 'sudden change', 'revelation', 'awakening'],
    upright_meaning: 'Sudden change, upheaval, chaos, revelation, awakening',
    reversed_meaning: 'Personal transformation, fear of change, averting disaster',
    description: 'The Tower represents sudden change and upheaval. Sometimes destruction is necessary for rebuilding.',
    love: "Sudden changes possible! Relationship mein koi big revelation aane wali hai. Thoda upheaval ho sakta hai but it's for the better. Wake up call hai!",
    career: "Sudden changes at work! Restructuring ya unexpected events. But it's for the better. Wake up moment! New beginning ke liye ready raho.",
    advice: "Change is coming! Resistance mat karo - embrace karo. Sudden upheavals better ke liye hote hain. Rebuild ready ho jao. Good things coming!",
    emotional_message: "Chaotic feel kar sakta hai par trust karo! Naya better build hoga. Sudden changes good ke liye hote hain. Rebuilding ka samay hai 💜",
    image: '🗼',
  },
  {
    id: 17,
    name: 'The Star',
    arcana: 'Major',
    suit: 'major',
    number: 17,
    keywords: ['hope', 'faith', 'renewal', 'inspiration'],
    upright_meaning: 'Hope, faith, purpose, renewal, spirituality',
    reversed_meaning: 'Lack of faith, despair, self-trust, hopelessness',
    description: 'The Star represents hope, faith, and renewal. She shines her light in the darkness.',
    love: "Hope aur faith! Love possible hai - trust karo! Naya connection aane wali hai. Faith rakho aur hope rakhna. Naya pyaar possible hai!",
    career: "Hope wapas aaya hai! Career mein naya opportunities. Faith rakhna - success aayegi. Renewal time hai. Good things coming soon!",
    advice: "Hope rakhna hai! Faith mat hato. Future ke liye positive raho. Naye opportunities aayenge. Trust the process - good things are coming!",
    emotional_message: "Hope is alive! Tumahara future bright hai. Cheezein improve honge - trust karo! Naya positive shuru hone wala hai. Hope mat kho! 💜",
    image: '⭐',
  },
  {
    id: 18,
    name: 'The Moon',
    arcana: 'Major',
    suit: 'major',
    number: 18,
    keywords: ['illusion', 'intuition', 'subconscious', 'fear'],
    upright_meaning: 'Illusion, fear, anxiety, subconscious, intuition',
    reversed_meaning: 'Release of fear, repressed emotion, inner truth, clarity',
    description: 'The Moon represents illusion and the subconscious. Things are not always as they seem.',
    love: "Confusion ho sakta hai! Check karo ki kya real hai aur kya illusion. Intuition suno. Emotions unclear hain - clarity dhundho.",
    career: "Professional confusion! Koi unclear situation - thoda wait karo. Check details carefully. Illusion na hona, reality dekho. Clarity ke liye time lo.",
    advice: "Confusion is normal - par reality aur illusion differentiate karo. Wait mat karo - socho clearly. What you see might not be real!",
    emotional_message: "Thoda uncertain feel kar sakta hai - that's okay! Apni intuition suno aur reality dekho. Clarity aayegi eventually. Trust your gut! 💜",
    image: '🌕',
  },
  {
    id: 19,
    name: 'The Sun',
    arcana: 'Major',
    suit: 'major',
    number: 19,
    keywords: ['joy', 'success', 'positivity', 'vitality'],
    upright_meaning: 'Positivity, fun, warmth, success, vitality',
    reversed_meaning: 'Inner child, feeling down, overly optimistic, sadness',
    description: 'The Sun represents positivity, joy, and success. It shines light on everything.',
    love: "Joy aur warmth! Relationship mein happy time aane wala hai. Fun aur positivity! Success guaranteed hai. Enjoy karo!",
    career: "Success coming! Recognition, achievement - sab milne wala hai. Positivity se kaam karo. Tumhara time is now!",
    advice: "Positivity embrace karo! Joy aur fun find karo. Success is coming! Smile rakhna hai. Bright times ahead!",
    emotional_message: "Tum gursel ho! Success tumahara hai. Joy aanewala hai. Positivity se dekho - sab bright hai! Your sunny days are here! 💜",
    image: '☀️',
  },
  {
    id: 20,
    name: 'Judgement',
    arcana: 'Major',
    suit: 'major',
    number: 20,
    keywords: ['rebirth', 'calling', 'judgement', 'awakening'],
    upright_meaning: 'Judgement, rebirth, inner calling, absolution',
    reversed_meaning: 'Self-doubt, inner critic, ignoring the call, doubt',
    description: 'Judgement represents rebirth and inner calling. It is time to answer your higher purpose.',
    love: "Inner calling suno! Relationship ke baare mein jo feeling aa rahi hai woh important hai. Rebirth - old version naya shuru hoga. Answer the call!",
    career: "Career calling! Next chapter aane wala hai. Inner calling se kaam karo. Rebirth - new beginning! Professional awakening time.",
    advice: "Inner calling suno! Tumhe kya karna hai woh feel karo. Rebirth - new you! Calling answer karo. It's time to start fresh!",
    emotional_message: "Tumhe kahin jaana hai! Inner calling loud hai - suno! Tum naya shuru kar sakte ho. Rebirth is coming - answer the call! 💜",
    image: '📯',
  },
  {
    id: 21,
    name: 'The World',
    arcana: 'Major',
    suit: 'major',
    number: 21,
    keywords: ['completion', 'accomplishment', 'integration', 'wholeness'],
    upright_meaning: 'Completion, integration, accomplishment, travel, wholeness',
    reversed_meaning: 'Seeking closure, delays, incomplete, emptiness',
    description: 'The World represents completion and accomplishment. You have reached the end of your journey.',
    love: "Completion! Relationship full circle aane wali hai. Wholeness mil jayegi. Travel possible hai with partner. Full circle!",
    career: "Completion! Goal achieve ho jayega. Project complete hone wala hai. Success mil jayegi. Travel opportunity bhi possible!",
    advice: "Goal achieve karne wale ho! Completion is near. Final push karo. Travel opportunities bhi possible hain. You've completed the journey!",
    emotional_message: "Tum jeet gaye! Completion is near. So much achieved! Travel bhi ho sakta hai. Full circle aap aa gaye - celebrate karo! 💜",
    image: '🌍',
  },

  // Wands - Ace through King
  {
    id: 22,
    name: 'Ace of Wands',
    arcana: 'Minor',
    suit: 'wands',
    number: 1,
    keywords: ['inspiration', 'opportunity', 'growth', 'potential'],
    upright_meaning: 'Inspiration, new opportunities, growth, potential',
    reversed_meaning: 'An emerging idea, lack of direction, delays, cancelled plans',
    description: 'The Ace of Wands represents new inspiration and opportunities. A spark of creativity is about to ignite.',
    love: "New spark! Naya attraction ya excitement. Koi naya person ya fresh start possible hai. Inspiration aane wala hai. New beginning is coming!",
    career: "New opportunities! Fresh projects, ideas ki shuruat. Growth potential hai. New direction mil sakta hai. Potential is huge!",
    advice: "Naya idea pursue karo! Inspiration ka paayega use karo. New opportunities apply karo. Spark ko flame banado. New beginnings ke liye ready raho!",
    emotional_message: "New spark ka time hai! Excitement wapas aane wala hai. Naya kuch shuru hone wala hai. Inspiration se full potential achieve karo! 💜",
    image: '🔥',
  },
  {
    id: 23,
    name: 'Two of Wands',
    arcana: 'Minor',
    suit: 'wands',
    number: 2,
    keywords: ['planning', 'progress', 'decisions', 'discovery'],
    upright_meaning: 'Future planning, progress, decisions, discovery',
    reversed_meaning: 'Personal goals, inner alignment, fear of unknown, poor planning',
    description: 'The Two of Wands represents planning and looking to the future. You have the world in your hands.',
    love: "Future planning! Relationship ke liye plans banao. Long-term thinking. Decision important hai. Future ke liye ready raho!",
    career: "Long-term planning! Career path decide karo. Future goals set karo. Progress planning ke saath hogi. Decisions carefully lo!",
    advice: "Future ke liye plan banao! Goals set karo. Progress systematically karo. Decision lo - which direction jana hai. Planning time!",
    emotional_message: "Tumhe clear chahiye ki kahaana jana hai! Socho, plan karo, aage badho. Future bright hai - plan carefully! 💜",
    image: '🌏',
  },
  {
    id: 24,
    name: 'Three of Wands',
    arcana: 'Minor',
    suit: 'wands',
    number: 3,
    keywords: ['expansion', 'progress', 'foresight', 'anticipation'],
    upright_meaning: 'Progress, expansion, foresight, overseas opportunities',
    reversed_meaning: 'Playing small, lack of foresight, delays, obstacles',
    description: 'The Three of Wands represents expansion and looking beyond the horizon. Your ships are coming in.',
    love: "Expansion! Relationship aage badh rahi hai. Overseas connection possible. More depth ke liye ready raho. Progress is happening!",
    career: "Expansion! Business grow kar sakta hai. Overseas opportunities. Growth is inevitable. Success coming from afar!",
    advice: "Vision se socho! Aage dekho. Expansion accept karo. Overseas opportunities explore karo. Growth embrace karo!",
    emotional_message: "Growth coming your way! Aage dekho - opportunities bahar hai. Expansion is happening! Vision rakhna important hai 💜",
    image: '🚢',
  },
  {
    id: 25,
    name: 'Four of Wands',
    arcana: 'Minor',
    suit: 'wands',
    number: 4,
    keywords: ['celebration', 'harmony', 'home', 'community'],
    upright_meaning: 'Celebration, harmony, marriage, home, community',
    reversed_meaning: 'Personal celebration, disharmony, conflict at home, instability',
    description: 'The Four of Wands represents celebration and harmony. It is a time of joy and community.',
    love: "Celebration! Engagement ya marriage vibes! Community mein celebrate. Home feeling. Harmony full hai. Happy times ahead!",
    career: "Team celebration! Work community strong hai. Success celebrate karo. Team harmony. Collaboration successful!",
    advice: "Celebrate karo! Harmony build karo. Community mein involve raho. Happiness share karo. Success enjoy karo!",
    emotional_message: "Party time! Happiness share karo. Community strong hai. Celebrate your achievements! 💜",
    image: '🎉',
  },
  {
    id: 26,
    name: 'Five of Wands',
    arcana: 'Minor',
    suit: 'wands',
    number: 5,
    keywords: ['conflict', 'competition', 'tension', 'disagreement'],
    upright_meaning: 'Conflict, disagreements, competition, tension, diversity',
    reversed_meaning: 'Inner conflict, conflict avoidance, tension release',
    description: 'The Five of Wands represents conflict and competition. There is tension and disagreement.',
    love: "Competition! Doosre logon se comparison. Darr mat lo - stand up for yourself. Healthy competition!",
    career: "Competition at work! Rivalries. But competition drives success. Stand out! Healthy competition is good.",
    advice: "Competition is natural. Apna path banao. Tension is temporary. Stand strong and compete fairly. Excellence will win!",
    emotional_message: "Competition se darr mat! Tum competetable ho. Apna game strong karo. Tension is part of growth! 💜",
    image: '⚔️',
  },
  {
    id: 27,
    name: 'Six of Wands',
    arcana: 'Minor',
    suit: 'wands',
    number: 6,
    keywords: ['success', 'recognition', 'achievement', 'victory'],
    upright_meaning: 'Success, public recognition, progress, self-confidence',
    reversed_meaning: 'Private achievement, selfish pride, fear of failure, no recognition',
    description: 'The Six of Wands represents success and public recognition. You are being celebrated for your achievements.',
    love: "Victory! Relationship mein success. Public recognition of love. Celebrate karo! Winning feeling!",
    career: "Victory! Public recognition. Promotion ya award. Success milne wala hai. Celebrated hogo!",
    advice: "Success achieve karo! Recognition milega. Celebrate karo. Tum jeet gaye! Public recognition is coming!",
    emotional_message: "Tum jeet gaye! Recognition tumahara hai. Success enjoy karo! People proud of you! 💜",
    image: '🏆',
  },
  {
    id: 28,
    name: 'Seven of Wands',
    arcana: 'Minor',
    suit: 'wands',
    number: 7,
    keywords: ['challenge', 'perseverance', 'defense', 'competition'],
    upright_meaning: 'Challenge, competition, perseverance, protective',
    reversed_meaning: 'Exhaustion, giving up, overwhelmed, defensive',
    description: 'The Seven of Wands represents challenge and standing your ground. You must defend your position.',
    love: "Defense needed! Relationship protect karo. Compete. Stand strong. Defender stance lena hoga!",
    career: "Defend your position! Challenges aayenge par tum handle karo. Stand firm. Perseverance wins!",
    advice: "Stand your ground! Defend karo apna position. Challenges aayenge par tum strong ho. Persevere karo!",
    emotional_message: "Tum strong ho! Challenges aayenge par handle kar loge. Stand firm! Defense karo aur fight karo! 💜",
    image: '🛡️',
  },
  {
    id: 29,
    name: 'Eight of Wands',
    arcana: 'Minor',
    suit: 'wands',
    number: 8,
    keywords: ['movement', 'speed', 'action', 'swiftness'],
    upright_meaning: 'Movement, fast-paced change, action, alignment, travel',
    reversed_meaning: 'Delays, frustration, awaiting, internal alignment',
    description: 'The Eight of Wands represents swift movement and change. Things are happening quickly.',
    love: "Fast action! Relationship mein speed badh gayi. Quick developments. Travel possible! Fast-moving energy!",
    career: "Fast-paced action! Quick decisions. Speed important hai. Travel for work. Fast changes!",
    advice: "Fast action lo! Quick decisions. Rushed mat karo par decisive raho. Movement is happening now!",
    emotional_message: "Speed badh gaya! Quick changes happening. Ready raho aur fast respond karo! 💜",
    image: '💨',
  },
  {
    id: 30,
    name: 'Nine of Wands',
    arcana: 'Minor',
    suit: 'wands',
    number: 9,
    keywords: ['resilience', 'persistence', 'courage', 'boundaries'],
    upright_meaning: 'Resilience, courage, persistence, test of faith, boundaries',
    reversed_meaning: 'Inner resources, exhaustion, overwhelmed, defensive',
    description: 'The Nine of Wands represents resilience and persistence. You are almost there, do not give up.',
    love: "Persistence! Relationship mein last push. Almost there - hold on. Boundary set karo. Persistence wins!",
    career: "Last stretch! Final push. Almost done! Keep going. Persistence will pay off. Near success!",
    advice: "Hold on! Almost there. Last push karo. Persistence rakhna hai. Near success - don't give up now!",
    emotional_message: "Tum almost there! Last bit mein strong raho. Persistence pay off karne wala hai. Hold on - you've got this! 💜",
    image: '🧱',
  },
  {
    id: 31,
    name: 'Ten of Wands',
    arcana: 'Minor',
    suit: 'wands',
    number: 10,
    keywords: ['burden', 'responsibility', 'hard work', 'completion'],
    upright_meaning: 'Burden, extra responsibility, hard work, completion',
    reversed_meaning: 'Inability to delegate, burnout, avoidance, burden-sharing',
    description: 'The Ten of Wands represents burden and hard work. You are carrying too much on your shoulders.',
    love: "Heavy responsibility! Relationship mein burden. Thoda lighten karo. Share karo responsibilities. Darr mat lo ask karo!",
    career: "Heavy workload! Responsibility badh gaya. Learn to delegate! Burnout warning. Share the load!",
    advice: "Share karo responsibility! Burden sab akele mat uthao. Delegate karo. Help mangna allowed hai!",
    emotional_message: "Thoda burden hatao! Help mangna allowed hai. Sab akele mat karo. Share karo - lighten the load! 💜",
    image: '🏋️',
  },
  {
    id: 32,
    name: 'Page of Wands',
    arcana: 'Minor',
    suit: 'wands',
    number: 11,
    keywords: ['enthusiasm', 'exploration', 'new ideas', 'courage'],
    upright_meaning: 'Enthusiasm, exploration, new ideas, courage, messenger',
    reversed_meaning: 'New ideas rejected, lack of direction,-immature, delayed messages',
    description: 'The Page of Wands represents enthusiasm, exploration, and new ideas. A messenger brings news.',
    love: "Fresh excitement! Naya attraction. Exploration phase. New person meets. Enthusiasm high!",
    career: "New ideas welcome! Fresh approach. Exploration. Tumhe message ya call aayega. New projects start!",
    advice: "Explore karo! New ideas welcome karo. Enthusiasm se kaam karo. Message wait karo. Fresh perspective lo!",
    emotional_message: "Fresh excitement! Naya kuch explore karo. Enthusiasm high hai - use it! New adventures await! 💜",
    image: '🏃',
  },
  {
    id: 33,
    name: 'Knight of Wands',
    arcana: 'Minor',
    suit: 'wands',
    number: 12,
    keywords: ['行动', '大胆', '热情', '冲动'],
    upright_meaning: 'Action, boldness, passion, charisma, adventure',
    reversed_meaning: 'Impulsiveness, recklessness, delays, frustration, impatience',
    description: 'The Knight of Wands represents action, boldness, and passion. They charge forward with energy.',
    love: "Bold action! Passionate approach. Direct. Tumhe koi milne wala hai. Adventure!",
    career: "Bold career moves! Passionate approach. Taking initiative. Adventure in work!",
    advice: "Bold action lo! Direct action. Passion se kaam karo. Tumhe energy hai - use it!",
    emotional_message: "Bold raho! Passion se action lo. Direct approach best hai. Adventure await karate hai! 💜",
    image: '🏎️',
  },
  {
    id: 34,
    name: 'Queen of Wands',
    arcana: 'Minor',
    suit: 'wands',
    number: 13,
    keywords: ['confidence', 'courage', 'creativity', ' warmth'],
    upright_meaning: 'Confidence, courage, creativity, warmth, determination',
    reversed_meaning: 'Insecurity, timidity, lack of confidence, overwhelmed',
    description: 'The Queen of Wands represents confidence, courage, and warmth. She leads with passion and warmth.',
    love: "Confident aur warm! Leadership role. Passionate lover. Confidence attract karte ho. Warm energy!",
    career: "Confident leadership! Creative fields. Warm environment create karo. Lead karo!",
    advice: "Confidence se lead karo! Warmth ke saath kaam karo. Creative raho. Bold leader bano. Confidence attract karta hai!",
    emotional_message: "Tum confident ho! Warmth aur courage se humesha strong lagti ho. Lead karo! Confidence is attractive 💜",
    image: '👩‍🦰',
  },
  {
    id: 35,
    name: 'King of Wands',
    arcana: 'Minor',
    suit: 'wands',
    number: 14,
    keywords: ['leadership', 'vision', 'entrepreneurship', 'authority'],
    upright_meaning: 'Leadership, vision, entrepreneurship, authority, control',
    reversed_meaning: 'Autocratic, impulsive, ruthless, poor leadership',
    description: 'The King of Wands represents leadership, vision, and entrepreneurship. A natural leader with bold vision.',
    love: "Natural leader! Relationship mein control. Visionary partner. Strong leadership. Control!",
    career: "Leadership position! Entrepreneurial moves. Visionary ideas. Authority - tum naturally lead karte ho!",
    advice: "Lead karo! Vision rakhna hai. Authority use karo. Natural leader ho tum - lead karo!",
    emotional_message: "Tum born leader ho! Vision se aur authority ke saath lead karo. You've got natural leadership! 💜",
    image: '👑',
  },

  // Cups - Ace through King
  {
    id: 36,
    name: 'Ace of Cups',
    arcana: 'Minor',
    suit: 'cups',
    number: 1,
    keywords: ['love', 'emotion', 'creativity', 'intuition'],
    upright_meaning: 'Love, new feelings, emotional awakening, creativity',
    reversed_meaning: 'Self-love, intuition, repressed emotions, emptiness',
    description: 'The Ace of Cups represents new emotional beginnings. Love and creativity are overflowing.',
    love: "New love! Emotional awakening. Naya pyaar shuru ho sakta hai. Open heart! New feelings!",
    career: "Creative fields friendly! Emotional intelligence important. New feelings about work. Creativity peak!",
    advice: "Heart open karo! New feelings embrace karo. Self-love bhi important hai. Openness le aao!",
    emotional_message: "Heart overflow ho raha hai! Naya love possible hai. Open heart rakhna hai. Feelings accept karo! 💜",
    image: '💧',
  },
  {
    id: 37,
    name: 'Two of Cups',
    arcana: 'Minor',
    suit: 'cups',
    number: 2,
    keywords: ['partnership', 'love', 'connection', 'attraction'],
    upright_meaning: 'Unified love, partnership, mutual attraction, connection',
    reversed_meaning: 'Self-love, break-up, disharmony, disconnection',
    description: 'The Two of Cups represents partnership and mutual attraction. Two souls are coming together.',
    love: "Partnership! Deep connection. Mutual attraction. Perfect match! Connection strong!",
    career: "Partnership opportunities! Collaborations work karenge. Team harmony. Connection builds success!",
    advice: "Partnership build karo! Connection strong rakhna hai. Mutual effort rakhna hai. Teamwork wins!",
    emotional_message: "Perfect connection mil raha hai! Partnership strong hai. Mutual attraction perfect hai. Open heart rakhna hai! 💜",
    image: '💑',
  },
  {
    id: 38,
    name: 'Three of Cups',
    arcana: 'Minor',
    suit: 'cups',
    number: 3,
    keywords: ['celebration', 'friendship', 'joy', 'community'],
    upright_meaning: 'Celebration, friendship, creativity, collaborations',
    reversed_meaning: 'Isolation, alone time, over-indulgence, gossip',
    description: 'The Three of Cups represents celebration and friendship. It is a time of joy with friends.',
    love: "Celebration with friends! Social love. Group happiness. Party vibes! Celebration!",
    career: "Team success! Social networking. Work friends ke saath celebrate. Collaboration success!",
    advice: "Celebrate karo! Friends ke saath time spend karo. Social networking strengthen karo. Joy share karo!",
    emotional_message: " Party time! Friends ke saath celebrate karo. Joy overflow ho raha hai! Community strong! 💜",
    image: '🥂',
  },
  {
    id: 39,
    name: 'Four of Cups',
    arcana: 'Minor',
    suit: 'cups',
    number: 4,
    keywords: ['meditation', 'contemplation', 'apathy', 'reflection'],
    upright_meaning: 'Meditation, contemplation, apathy, reevaluation',
    reversed_meaning: 'Retreat, withdrawal, checking in, new opportunities',
    description: 'The Four of Cups represents meditation and contemplation. You are being offered something new.',
    love: "Reevaluation time! Relationship socho. Apathy - check karo. New option available. Reflection!",
    career: "Contemplation! Career socho. Apathy - check karo. New option available hai. Reflection!",
    advice: "Socho! Reflect karo. Kya changa hai, kya nahi. New options evaluate karo. Contemplation time!",
    emotional_message: "Take time to think! Reflection important hai. Socho clearly. Apathy se bahar ao! 💜",
    image: '🧘',
  },
  {
    id: 40,
    name: 'Five of Cups',
    arcana: 'Minor',
    suit: 'cups',
    number: 5,
    keywords: ['regret', 'loss', 'disappointment', 'grief'],
    upright_meaning: 'Regret, failure, disappointment, pessimism, loss',
    reversed_meaning: 'Personal setbacks, self-forgiveness, moving on, hope',
    description: 'The Five of Cups represents regret and disappointment. You are focused on what is lost.',
    love: "Disappointment! Past loss. Regret. Moving on important. Hope bhi hai!",
    career: "Professional disappointment. Setbacks. But moving on important. Success future mein hai!",
    advice: "Move on! Past mistakes se seekho. Regret mat rakhna. Future focus karo. Hope rakhna!",
    emotional_message: "Loss se ghabrao mat! Moving on important hai. Past se seekho. Hope rakhna - better future ahead! 💜",
    image: '😢',
  },
  {
    id: 41,
    name: 'Six of Cups',
    arcana: 'Minor',
    suit: 'cups',
    number: 6,
    keywords: ['nostalgia', 'childhood', 'innocence', 'memories'],
    upright_meaning: 'Revisiting the past, childhood memories, innocence, joy',
    reversed_meaning: 'Living in the past, unrealistic, naïveté, stuck',
    description: 'The Six of Cups represents nostalgia and childhood memories. The past is calling.',
    love: "Nostalgia! Ex ya old friend. Past memories. Innocent love feelings. Sweet nostalgia!",
    career: "Past connections helpful! Old colleagues. Nostalgia motivates. Past experience useful!",
    advice: "Nostalgia appreciate karo par past mein stuck mat raho. Past use karo to build future!",
    emotional_message: "Sweet memories valuable hain! Past appreciate karo. But future ke liye bhi socho. Sweet nostalgia! 💜",
    image: '🎠',
  },
  {
    id: 42,
    name: 'Seven of Cups',
    arcana: 'Minor',
    suit: 'cups',
    number: 7,
    keywords: ['choices', 'illusion', 'opportunities', 'dreams'],
    upright_meaning: 'Opportunities, choices, wishful thinking, illusion',
    reversed_meaning: 'Clarity, focus, scattered, overwhelmed by choices',
    description: 'The Seven of Cups represents opportunities and choices. Not everything is as it seems.',
    love: "Choices! Options available. Illusion se beware. Focus on reality. Choose wisely!",
    career: "Multiple opportunities! Decision time. Illusion se beware. Focus required!",
    advice: "Choices evaluate karo! Clarity dhundho. Focus rakhna hai. Illusion se bachna hai!",
    emotional_message: "Choices bahar hain! Par focus important hai. Socho clearly. Illusion se beware! 💜",
    image: '☁️',
  },
  {
    id: 43,
    name: 'Eight of Cups',
    arcana: 'Minor',
    suit: 'cups',
    number: 8,
    keywords: ['abandonment', 'withdrawal', 'letting go', 'moving on'],
    upright_meaning: 'Disappointment, abandonment, withdrawal, escapism',
    reversed_meaning: 'Trying one more time, indecision, aimless drifting',
    description: 'The Eight of Cups represents walking away from what no longer serves you.',
    love: "Walking away! Old relationship end. Disappointment. Letting go time. Move on!",
    career: "Career change! Leaving old job. Disappointment. New chapter. Moving on!",
    advice: "Let go karo! Jo serve nahi kar raha woh chhod do. New chapter ke liye ready raho. Move on!",
    emotional_message: "Letting go time! Past se move on karo. Naya better chapter await hai. Walk away for your happiness! 💜",
    image: '🚶',
  },
  {
    id: 44,
    name: 'Nine of Cups',
    arcana: 'Minor',
    suit: 'cups',
    number: 9,
    keywords: ['contentment', 'satisfaction', 'gratitude', 'wishes'],
    upright_meaning: 'Contentment, satisfaction, gratitude, wish fulfillment',
    reversed_meaning: 'Inner happiness, materialism, dissatisfaction, arrogance',
    description: 'The Nine of Cups represents contentment and wishes coming true. Your dreams are manifesting.',
    love: "Satisfaction! Deep contentment. Wish fulfillment. Love complete. Gratitude!",
    career: "Professional satisfaction! Success achieved. Contentment. Wish fulfillment!",
    advice: "Appreciate karo! Gratitude rakhna hai. Contentment find karo. Wish fulfillment coming!",
    emotional_message: "Contentment mil gaya! Satisfaction feel karo. Gratitude rakhna. Tum jeet gaye! 💜",
    image: '😊',
  },
  {
    id: 45,
    name: 'Ten of Cups',
    arcana: 'Minor',
    suit: 'cups',
    number: 10,
    keywords: ['harmony', 'love', 'family', 'bliss'],
    upright_meaning: 'Divine love, blissful relationships, harmony, family',
    reversed_meaning: 'Disconnection, break-up, family conflict, misalignment',
    description: 'The Ten of Cups represents divine love and harmony. Your family is blessed.',
    love: "Family harmony! Blissful love. Perfect family vibes. Divine connection! Long-term love!",
    career: "Team harmony! Work family. Blissful environment. Strong team bonds!",
    advice: "Family value karo! Harmony maintain karo. Love share karo. Divine blessings!",
    emotional_message: "Family love complete! Bliss feel karo. Harmony perfect hai. Divine blessings! 💜",
    image: '🌈',
  },
  {
    id: 46,
    name: 'Page of Cups',
    arcana: 'Minor',
    suit: 'cups',
    number: 11,
    keywords: ['sensitivity', 'creativity', 'emotional', 'messenger'],
    upright_meaning: 'Creative, sensitive, emotional messenger, new feelings',
    reversed_meaning: 'Immature, overly emotional, sensitive, rejection',
    description: 'The Page of Cups represents new emotional beginnings and sensitivity. A sensitive messenger arrives.',
    love: "New feelings! Sensitive approach. New romantic messenger. Openness! New emotional chapter!",
    career: "Creative opportunities! Emotional intelligence useful. New feelings. Creative input valuable!",
    advice: "Sensitivity embrace karo! New creative ideas welcome karo. Open heart rakhna!",
    emotional_message: "New feelings! Sensitive hone se koi baat nahi. Openness positive hai. Feel freely! 💜",
    image: '🧑',
  },
  {
    id: 47,
    name: 'Knight of Cups',
    arcana: 'Minor',
    suit: 'cups',
    number: 12,
    keywords: ['romantic', 'emotional', 'dreamer', 'sensitive'],
    upright_meaning: 'Romantic, dreamer, emotional, idealist, sensitive',
    reversed_meaning: 'Unreliable, moody, emotional, disappointment, dreamer',
    description: 'The Knight of Cups represents romance, emotion, and idealism. A romantic seeker.',
    love: "Romance incoming! Idealistic love. Deep emotions. Dreamy vibes! Romantic adventure!",
    career: "Creative idealist! Emotionally intelligent. Romantic approach to work. Passionate!",
    advice: "Romance pursue karo! Idealism valuable hai. Emotions embrace karo. Dream big!",
    emotional_message: "Romance feel karo! Ideal love possible hai. Open heart rakhna. Dreams come true! 💜",
    image: '🎎',
  },
  {
    id: 48,
    name: 'Queen of Cups',
    arcana: 'Minor',
    suit: 'cups',
    number: 13,
    keywords: ['compassion', 'intuitive', 'nurturing', 'emotional'],
    upright_meaning: 'Compassion, intuitive, nurturing, emotionally secure, caring',
    reversed_meaning: 'Insecure, codependent, emotionally drained, martyr',
    description: 'The Queen of Cups represents compassion, intuition, and emotional nurturing.',
    love: "Nurturing love! Deep compassion. Intuitive partner. Caring vibes. Emotional security!",
    career: "Nurturing environment! Emotional support roles. Compassionate leadership. Intuition helpful!",
    advice: "Compassion rakhna hai! Intuition suno. Care karo. Emotional intelligence valuable!",
    emotional_message: "Tum naturally nurturing ho! Compassionate heart valuable hai. Intuition strong. Care find karo! 💜",
    image: '👩‍🎨',
  },
  {
    id: 49,
    name: 'King of Cups',
    arcana: 'Minor',
    suit: 'cups',
    number: 14,
    keywords: ['emotional mastery', 'wisdom', 'calm', 'leadership'],
    upright_meaning: 'Emotional mastery, wisdom, calm, balanced leadership',
    reversed_meaning: 'Emotional instability, moodiness, domination, cold',
    description: 'The King of Cups represents emotional mastery and wisdom. A balanced emotional leader.',
    love: "Emotionally wise! Balanced love. Mature emotions. Wisdom in love. Emotional mastery!",
    career: "Emotionally wise leadership! Calm under pressure. Balanced approach. Wisdom valued!",
    advice: "Emotional mastery achieve karo! Calm rakhna hai. Wisdom use karo. Balanced leader bano!",
    emotional_message: "Tum emotionally wise ho! Calmness valuable hai. Wisdom se sab handle karo! 💜",
    image: '👑',
  },

  // Swords - Ace through King
  {
    id: 50,
    name: 'Ace of Swords',
    arcana: 'Minor',
    suit: 'swords',
    number: 1,
    keywords: ['clarity', 'breakthrough', 'truth', 'ideas'],
    upright_meaning: 'Breakthrough, clarity, sharp mind, new ideas',
    reversed_meaning: 'Inner clarity, confusion, clouded judgement, misunderstanding',
    description: 'The Ace of Swords represents mental clarity and breakthrough. The truth is revealed.',
    love: "Clarity! Relationship clear hoga. Truth reveal. Breakthrough in love. Clear communication!",
    career: "Mental breakthrough! Clarity in work. Sharp ideas. Truth reveal. Clear thinking!",
    advice: "Clarity achieve karo! Truth face karo. Clear thinking valuable hai. Breakthrough incoming!",
    emotional_message: "Clarity mil gaya! Truth clear hai. Breakthrough aaya. Clear think karo! 💜",
    image: '⚔️',
  },
  {
    id: 51,
    name: 'Two of Swords',
    arcana: 'Minor',
    suit: 'swords',
    number: 2,
    keywords: ['choices', 'indecision', 'stalemate', 'balance'],
    upright_meaning: 'Difficult choices, indecision, stalemate, blocked emotions',
    reversed_meaning: 'Indecision, confusion, analysis paralysis, information overload',
    description: 'The Two of Swords represents difficult choices and indecision. You are at a crossroads.',
    love: "Choice dilemma! Decision time. Socho carefully. Clear communication needed!",
    career: "Career decision! Indecision. Crossroads. Choice important!",
    advice: "Decision lo! Indecision se bahar ao. Choos wisely. Clear thinking required!",
    emotional_message: "Choice important hai! Indecision se bahar ao. Socho calmly. Decision lo! 💜",
    image: '🤔',
  },
  {
    id: 52,
    name: 'Three of Swords',
    arcana: 'Minor',
    suit: 'swords',
    number: 3,
    keywords: ['heartbreak', 'sorrow', 'grief', 'pain'],
    upright_meaning: 'Heartbreak, emotional pain, sorrow, grief, hurt',
    reversed_meaning: 'Negative self-talk, healing, forgiveness, releasing pain',
    description: 'The Three of Swords represents heartbreak and sorrow. Pain is necessary for growth.',
    love: "Heartbreak! Emotional pain. But healing time. Forgive and move on!",
    career: "Professional heartbreak. Loss. Painful but temporary. Healing!",
    advice: "Pain feel karo! Healing start karo. Forgive karo. Move forward!",
    emotional_message: "Pain temporary hai! Healing start ho gaya. Forgive karo. Move on for your peace! 💜",
    image: '💔',
  },
  {
    id: 53,
    name: 'Four of Swords',
    arcana: 'Minor',
    suit: 'swords',
    number: 4,
    keywords: ['rest', 'relaxation', 'meditation', 'recovery'],
    upright_meaning: 'Rest, relaxation, meditation, contemplation, recuperation',
    reversed_meaning: 'Exhaustion, burnout, unrest, unable to relax',
    description: 'The Four of Swords represents rest and recuperation. Take time to recover.',
    love: "Rest time! Relationship relax. Take it easy. Peaceful time!",
    career: "Work rest! Burnout se bachna. Rest required. Recovery time!",
    advice: "Rest karo! Relax required. Recovery important. Take it easy!",
    emotional_message: "Rest zaroori hai! Relax karo. Thoda rest lekar recovery hogi. Self-care first! 💜",
    image: '😴',
  },
  {
    id: 54,
    name: 'Five of Swords',
    arcana: 'Minor',
    suit: 'swords',
    number: 5,
    keywords: ['conflict', 'defeat', 'competition', 'betrayal'],
    upright_meaning: 'Conflict, disagreements, competition, defeat, winning at all costs',
    reversed_meaning: 'Reconciliation, making amends, moving on, forgiveness',
    description: 'The Five of Swords represents conflict and defeat. Not every battle is worth fighting.',
    love: "Conflict! Arguments. Competition. But reconciliation possible. Moving on!",
    career: "Work conflicts. Competition. But move on! Reconciliation possible!",
    advice: "Conflict avoid karo! Some battles not worth fighting. Move on! Reconciliation valuable!",
    emotional_message: "Conflickt darr ke mat! Some things not worth fighting. Reconciliation try karo. Move on! 💜",
    image: '😤',
  },
  {
    id: 55,
    name: 'Six of Swords',
    arcana: 'Minor',
    suit: 'swords',
    number: 6,
    keywords: ['transition', 'change', 'moving on', 'passage'],
    upright_meaning: 'Transition, change, rite of passage, releasing baggage',
    reversed_meaning: 'Stuck, holding on, unfinished business, resisting change',
    description: 'The Six of Swords represents transition and moving on. You are leaving troubled waters behind.',
    love: "Transition! Old se new. Moving on. New chapter!",
    career: "Career transition! Change. New chapter. Transition phase!",
    advice: "Transition accept karo! Move forward. Hold on mat karo. New chapter!",
    emotional_message: "New chapter! Transition phase. Move forward. Leaving old behind. Fresh start! 💜",
    image: '⛵',
  },
  {
    name: 'Seven of Swords',
    arcana: 'Minor',
    suit: 'swords',
    number: 7,
    id: 56,
    keywords: ['deception', 'betrayal', 'stealth', 'strategy'],
    upright_meaning: 'Betrayal, deception, getting away with something, stealth',
    reversed_meaning: 'Imposter syndrome, self-deceit, keeping secrets, confession',
    description: 'The Seven of Swords represents deception and betrayal. Someone is not being honest.',
    love: "Deception possible! Check honesty. Koi secret. Be careful!",
    career: "Deception at work. Check honesty. Be careful of being deceived!",
    advice: "Deception se beware! Honesty value karo. Secrets will come out. Careful raho!",
    emotional_message: "Honesty important hai! Check koi deception to nahi. Careful raho. Honesty wins! 💜",
    image: '🤫',
  },
  {
    id: 57,
    name: 'Eight of Swords',
    arcana: 'Minor',
    suit: 'swords',
    number: 8,
    keywords: ['restriction', 'trapped', 'victim', 'limitation'],
    upright_meaning: 'Negative thoughts, self-imposed restriction, imprisonment, victim mentality',
    reversed_meaning: 'Self-limiting beliefs, breaking free, new perspective, liberation',
    description: 'The Eight of Swords represents feeling trapped. The prison is of your own making.',
    love: "Trapped feeling! Self restrictions. Breaking free needed. New perspective!",
    career: "Self-made restrictions! Career mein trapped feel. Break free!",
    advice: "Self restrictions tod do! Breaking free. New perspective adopt karo. Liberation!",
    emotional_message: "Tum free ho! Restrictions tumhare apne hain. Break free karo! Liberation time! 💜",
    image: '⛓️',
  },
  {
    id: 58,
    name: 'Nine of Swords',
    arcana: 'Minor',
    suit: 'swords',
    number: 9,
    keywords: ['anxiety', 'worry', 'fear', 'nightmares'],
    upright_meaning: 'Anxiety, worry, fear, depression, nightmares',
    reversed_meaning: 'Inner turmoil, facing fears, hope, recovery',
    description: 'The Nine of Swords represents anxiety and worry. Your fears are keeping you up at night.',
    love: "Anxiety! Worry about relationship. Fears face karo. Ho jayega!",
    career: "Work anxiety! Worry about success. Face fears!",
    advice: "Anxiety face karo! Fears se fight karo. Hope rakhna hai. Recovery possible!",
    emotional_message: "Anxiety normal hai! Par hope mat hato. Fear face karo. Everything will be okay! 💜",
    image: '😰',
  },
  {
    id: 59,
    name: 'Ten of Swords',
    arcana: 'Minor',
    suit: 'swords',
    number: 10,
    keywords: ['endings', 'pain', 'betrayal', 'crisis'],
    upright_meaning: 'Painful endings, deep wounds, betrayal, loss, crisis',
    reversed_meaning: 'Recovery, regeneration, hope, avoiding end',
    description: 'The Ten of Swords represents painful endings. The worst is over, now you can heal.',
    love: "Painful ending! But it's okay. Recovery start. New beginning!",
    career: "Painful ending! Career crisis. But recovery start. New chapter!",
    advice: "Endings painful hote hain. But recovery start. Hope rakhna. Moving forward!",
    emotional_message: "Worst over hai! Recovery shuru ho gaya. Hope rakhna. New beginning incoming! 💜",
    image: '🗡️',
  },
  {
    id: 60,
    name: 'Page of Swords',
    arcana: 'Minor',
    suit: 'swords',
    number: 11,
    keywords: ['curiosity', 'communication', 'ideas', 'messenger'],
    upright_meaning: 'Curious, communicative, new ideas, messenger, truth-seeker',
    reversed_meaning: 'Gossip, immaturity, misused communication, deception',
    description: 'The Page of Swords represents curiosity, communication, and new ideas. A youthful messenger arrives.',
    love: "Curious energy! New ideas. Communication key. Open chat!",
    career: "Curious mind! New ideas. Communication important. Fresh perspective!",
    advice: "Curiosity explore karo! Communication improve karo. New ideas welcome!",
    emotional_message: "Curious raho! Communication important hai. New ideas explore karo. Learn and grow! 💜",
    image: '🧑‍🎓',
  },
  {
    id: 61,
    name: 'Knight of Swords',
    arcana: 'Minor',
    suit: 'swords',
    number: 12,
    keywords: ['intellectual', 'communication', 'debate', 'aggressive'],
    upright_meaning: 'Intellectual, aggressive, communication, debate, quick-thinking',
    reversed_meaning: 'Brutal, harsh, verbally aggressive, cold logic',
    description: 'The Knight of Swords represents intellectual aggression and debate. A quick-thinking messenger.',
    love: "Debate energy! Direct communication. Intellect attract. Quick!",
    career: "Intellectual battle! Debates. Quick thinking. Communication skills!",
    advice: "Quick thinking use karo! Intellectual approach. Communication powerful hai. Direct raho!",
    emotional_message: "Quick thinking valuable! Direct communication best. Intellect use karo. Be quick! 💜",
    image: '🏇',
  },
  {
    id: 62,
    name: 'Queen of Swords',
    arcana: 'Minor',
    suit: 'swords',
    number: 13,
    keywords: ['intelligence', 'independence', 'communication', 'sharp'],
    upright_meaning: 'Intelligence, independence, clear communication, sharp mind',
    reversed_meaning: 'Cold, harsh, bitter, manipulative, insensitive',
    description: 'The Queen of Swords represents intelligence and clear communication. A sharp, independent thinker.',
    love: "Independent aura! Clear communication. Sharp mind. Intellect attracts!",
    career: "Sharp intelligence! Clear communication. Independent work. Excel!",
    advice: "Independence value karo! Clear communication. Sharp mind use karo. Be independent!",
    emotional_message: "Independent aur sharp! Tum naturally intelligent ho. Clear communication valuable! 💜",
    image: '👸',
  },
  {
    id: 63,
    name: 'King of Swords',
    arcana: 'Minor',
    suit: 'swords',
    number: 14,
    keywords: ['authority', 'intellect', 'logic', 'leadership'],
    upright_meaning: 'Authority, clear thinking, intellectual leadership, logic',
    reversed_meaning: 'Tyranny, harsh judgment, cold logic, manipulation',
    description: 'The King of Swords represents authority, intellect, and logical leadership.',
    love: "Logical love! Clear thinking. Authority. Intellectual connection!",
    career: "Intellectual leadership! Authority. Logic over emotion. Clear thinking wins!",
    advice: "Authority achieve karo! Logic use karo. Clear thinking. Lead with intellect!",
    emotional_message: "Logical leadership! Authority naturally milta hai. Clear thinker bano. Intellect is power! 💜",
    image: '👑',
  },

  // Pentacles - Ace through King
  {
    id: 64,
    name: 'Ace of Pentacles',
    arcana: 'Minor',
    suit: 'pentacles',
    number: 1,
    keywords: ['opportunity', 'abundance', 'prosperity', 'stability'],
    upright_meaning: 'New financial opportunity, manifestation, abundance, stability',
    reversed_meaning: 'Lost opportunity, lack of planning, scarcity mindset',
    description: 'The Ace of Pentacles represents new financial opportunities. Prosperity is within reach.',
    love: "Material stability! Abundance in love. Security. Stable relationship. Abundance!",
    career: "Financial opportunity! New income. Abundance. Stable career. Manifestation!",
    advice: "Opportunity grab karo! Abundance manifest karo. Stability achieve karo. Act now!",
    emotional_message: "Abundance coming! Financial opportunities milenge. Stability achieve karo. Manifest abundance! 💜",
    image: '💰',
  },
  {
    id: 65,
    name: 'Two of Pentacles',
    arcana: 'Minor',
    suit: 'pentacles',
    number: 2,
    keywords: ['balance', 'priorities', 'adaptability', 'juggling'],
    upright_meaning: 'Multiple priorities, time management, prioritization, adaptability',
    reversed_meaning: 'Over-committed, disorganization, reprioritization, overwhelmed',
    description: 'The Two of Pentacles represents juggling multiple priorities. Balance is key.',
    love: "Balance! Multiple commitments. Prioritize. Adaptability!",
    career: "Multi-tasking! Juggling priorities. Work-life balance. Adapt!",
    advice: "Balance maintain karo! Priorities set karo. Adaptability valuable! Juggling karo!",
    emotional_message: "Balance important! Multi-tasking OK hai. Adaptability valuable! Prioritize karo! 💜",
    image: '🤹',
  },
  {
    id: 66,
    name: 'Three of Pentacles',
    arcana: 'Minor',
    suit: 'pentacles',
    number: 3,
    keywords: ['teamwork', 'collaboration', 'learning', 'craft'],
    upright_meaning: 'Teamwork, collaboration, learning, implementation',
    reversed_meaning: 'Disharmony, misalignment, working alone, lack of help',
    description: 'The Three of Pentacles represents teamwork and collaboration. Together you can achieve more.',
    love: "Teamwork! Collaboration strong. Partner help. Working together!",
    career: "Teamwork! Collaboration. Skill building. Working together!",
    advice: "Teamwork embrace karo! Collaboration valuable. Help seekna. Together stronger!",
    emotional_message: "Team player bano! Collaboration se success. Help seekna allowed hai. Together achieve! 💜",
    image: '👷',
  },
  {
    id: 67,
    name: 'Four of Pentacles',
    arcana: 'Minor',
    suit: 'pentacles',
    number: 4,
    keywords: ['security', 'control', 'conservation', 'stability'],
    upright_meaning: 'Saving money, security, conservatism, scarcity, control',
    reversed_meaning: 'Over-spending, greed, self-protection, stinginess',
    description: 'The Four of Pentacles represents security and control. You are holding on too tightly.',
    love: "Security needed! Control. Holding too tight? Save wisely!",
    career: "Financial control! Saving. Security. But don't be too tight!",
    advice: "Security important, par tight mat raho! Balance rakhna. Generous bhi raho!",
    emotional_message: "Security valuable hai, par tight mat raho! Balance maintain karo. Open handed bano! 💜",
    image: '🏦',
  },
  {
    id: 68,
    name: 'Five of Pentacles',
    arcana: 'Minor',
    suit: 'pentacles',
    number: 5,
    keywords: ['hardship', 'poverty', 'loss', 'isolation'],
    upright_meaning: 'Financial loss, poverty, lack mindset, isolation, worry',
    reversed_meaning: 'Recovery from financial loss, spiritual wealth, help arriving',
    description: 'The Five of Pentacles represents financial hardship. Help is available if you ask.',
    love: "Tough times! Financial stress. But support mil jayega. Help accept karo!",
    career: "Financial hardship! Loss. Hard times. But help coming!",
    advice: "Tough times, par help available hai! Seek help! Recovery coming. Hope rakhna!",
    emotional_message: "Tough times but temporary! Help mil jayega. Recovery coming. Hope rakhna! 💜",
    image: '❄️',
  },
  {
    id: 69,
    name: 'Six of Pentacles',
    arcana: 'Minor',
    suit: 'pentacles',
    number: 6,
    keywords: ['generosity', 'giving', 'receiving', 'charity'],
    upright_meaning: 'Giving, receiving, sharing wealth, generosity, charity',
    reversed_meaning: 'Self-care, unpaid debts, one-sided charity, indebted',
    description: 'The Six of Pentacles represents generosity and sharing. Give and you shall receive.',
    love: "Generosity! Give and receive. Balanced exchange. Charity in love!",
    career: "Generosity! Sharing wealth. Charitable work. Receive and give!",
    advice: "Generosity practice karo! Give and receive. Balance maintain!",
    emotional_message: "Generous raho! Give and receive. Balance important. Charity brings abundance! 💜",
    image: '🎁',
  },
  {
    id: 70,
    name: 'Seven of Pentacles',
    arcana: 'Minor',
    suit: 'pentacles',
    number: 7,
    keywords: ['patience', 'investment', 'vision', 'perseverance'],
    upright_meaning: 'Long-term view, sustainable results, perseverance, investment',
    reversed_meaning: 'Lack of patience, impatient, stuck, poor investment',
    description: 'The Seven of Pentacles represents patience and long-term vision. Your efforts will pay off.',
    love: "Long-term view! Investment in love. Patience. Future planning!",
    career: "Long-term investment! Patience. Slow and steady. Vision required!",
    advice: "Patience rakhna hai! Long-term invest. Vision maintain. Persevere!",
    emotional_message: "Patience pays! Long-term view valuable. Keep investing. Results coming! 💜",
    image: '🌱',
  },
  {
    id: 71,
    name: 'Eight of Pentacles',
    arcana: 'Minor',
    suit: 'pentacles',
    number: 8,
    keywords: ['mastery', 'skill', 'practice', 'dedication'],
    upright_meaning: 'Apprenticeship, repetitive tasks, mastery, skill development',
    reversed_meaning: 'Lack of skill, misdirected effort, no mastery, lazy',
    description: 'The Eight of Pentacles represents mastery through practice. Keep honing your skills.',
    love: "Skill building! Learning love. Practice. Mastery in relationships!",
    career: "Skill development! Mastery. Practice. Dedication. Learn!",
    advice: "Practice karo! Skill develop karo. Mastery seekho. Dedicated raho!",
    emotional_message: "Skill build karo! Practice makes perfect. Mastery achievable. Keep learning! 💜",
    image: '🔨',
  },
  {
    id: 72,
    name: 'Nine of Pentacles',
    arcana: 'Minor',
    suit: 'pentacles',
    number: 9,
    keywords: ['abundance', 'luxury', 'independence', 'success'],
    upright_meaning: 'Abundance, luxury, self-sufficiency, financial independence',
    reversed_meaning: 'Self-worth issues, overworking, hustle, dependants',
    description: 'The Nine of Pentacles represents abundance and luxury. You have achieved financial independence.',
    love: "Self-sufficiency! Abundance in love. Luxury vibe. Independence!",
    career: "Abundance! Success achieved. Luxury. Financial independence!",
    advice: "Self-sufficiency achieve karo! Abundance enjoy karo. Independence valuable!",
    emotional_message: "Achievement mili! Abundance tumahara hai. Success enjoy karo! Abundance achieved! 💜",
    image: '💎',
  },
  {
    id: 73,
    name: 'Ten of Pentacles',
    arcana: 'Minor',
    suit: 'pentacles',
    number: 10,
    keywords: ['wealth', 'family', 'legacy', 'security'],
    upright_meaning: 'Wealth, financial security, family, long-term success, contribution',
    reversed_meaning: 'Financial loss, family conflict, greed, poor legacy',
    description: 'The Ten of Pentacles represents wealth and family legacy. You have built something lasting.',
    love: "Family wealth! Legacy. Long-term security. Family harmony. Abundance!",
    career: "Wealth achieved! Family business. Legacy. Long-term security!",
    advice: "Legacy build karo! Family value karo. Long-term wealth. Security achieve!",
    emotional_message: "Legacy achieve! Family wealth. Long-term security. You've built something lasting! 💜",
    image: '🏰',
  },
  {
    id: 74,
    name: 'Page of Pentacles',
    arcana: 'Minor',
    suit: 'pentacles',
    number: 11,
    keywords: ['learning', 'practical', 'growth', 'messenger'],
    upright_meaning: 'Practical learner, new opportunity, growth, messenger',
    reversed_meaning: 'Lack of growth, laziness, missed opportunity, immature',
    description: 'The Page of Pentacles represents new opportunities and practical learning.',
    love: "New practical love! Learning. Growth opportunity. New person!",
    career: "Practical opportunity! Learning. Growth. New start in work!",
    advice: "Practical learning pursue karo! Opportunity grab. Growth welcome!",
    emotional_message: "Growth opportunity! Practical learning. New chapter. Learn and grow! 💜",
    image: '🧑‍🌾',
  },
  {
    id: 75,
    name: 'Knight of Pentacles',
    arcana: 'Minor',
    suit: 'pentacles',
    number: 12,
    keywords: ['reliability', 'hard work', 'dedication', 'practical'],
    upright_meaning: 'Reliability, hard work, dedication, practical, patient',
    reversed_meaning: 'Lazy, unreliability, stagnation, work avoidance',
    description: 'The Knight of Pentacles represents reliability and hard work. A dependable worker.',
    love: "Reliable partner! Hardworking. Dedicated. Stable. Patient.",
    career: "Reliable worker! Hard work. Dedication. Practical. Patient!",
    advice: "Reliable raho! Hard work karo. Dedication valuable. Patient raho!",
    emotional_message: "Reliability valuable! Tum trustworthy ho. Hard work pays off. Keep going! 💜",
    image: '🏎️',
  },
  {
    id: 76,
    name: 'Queen of Pentacles',
    arcana: 'Minor',
    suit: 'pentacles',
    number: 13,
    keywords: ['nurturing', 'practical', 'abundant', 'security'],
    upright_meaning: 'Nurturing, practical, abundant, secure, motherly',
    reversed_meaning: 'Clingy, smothering, possessive, insecure, financial issues',
    description: 'The Queen of Pentacles represents nurturing, practicality, and abundance.',
    love: "Nurturing love! Practical. Secure. Abundant. Motherly care!",
    career: "Practical nurturing! Abundance. Security. Care giving. Stable!",
    advice: "Nurturing value karo! Practical raho. Security aim karo. Abundance!",
    emotional_message: "Nurturing aur practical! Security important. Abundance achievable. Care and provide! 💜",
    image: '👩‍🌾',
  },
  {
    id: 77,
    name: 'King of Pentacles',
    arcana: 'Minor',
    suit: 'pentacles',
    number: 14,
    keywords: ['wealth', 'business', 'leadership', 'stability'],
    upright_meaning: 'Wealthy, business-minded, stable, successful, authority',
    reversed_meaning: 'Wealth abuse, greedy, controlling, materialistic, rigid',
    description: 'The King of Pentacles represents wealth, business acumen, and stability.',
    love: "Stable, wealthy love! Successful partner. Security. Abundance!",
    career: "Business leadership! Wealth. Stability. Authority. Success!",
    advice: "Business leader bano! Wealth build karo. Stability achieve. Authority!",
    emotional_message: "Success achieved! Wealthy aur stable. Authority naturally. You've made it! 💜",
    image: '👑',
  },
]

export function getRandomCards(count: number = 3): TarotCard[] {
  const shuffled = [...tarotCards].sort(() => Math.random() - 0.5)
  return shuffled.slice(0, count)
}

export function getCardById(id: number): TarotCard | undefined {
  return tarotCards.find((card) => card.id === id)
}